
### Create a new document
POST https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Start App4 videos",
  "important": true
}

### Create a new document
POST https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Apply at more jobs",
  "important": true,
  "completed": false
}

### Create a new document
POST https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "Watch the rest of Lex Friedman podcast",
  "important": false,
  "completed": false
}

### GET All documents
GET https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo.json

### GET One document by key
GET https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo/-NQc99OVH5eyAvE97FFY.json

### UPDATE document - will replace all properties with the properties in the request body - if you miss a property it will be removed
PUT https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo/-NQc99OVH5eyAvE97FFY.json
Content-Type: application/json

{
  "task": "Watch the rest of the Same Harris and Lex Friedman podcast",
  "important": false
}

### DELETE document - use this if you want to delete a document
DELETE https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo/-NQc99OVH5eyAvE97FFY.json


### PATCH document - use this if you want to update some of the properties but not all of them
PATCH https://dmit2015-1222-skrlj-demos-default-rtdb.firebaseio.com/Todo/-NQc8niEz4UlOpG5uSvw.json
Content-Type: application/json

{
  "completed": false
}